<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PUTapigraphicgraphicActualizar un gr_f492c5</name>
   <tag></tag>
   <elementGuidId>b0ed760f-1602-49ef-a09d-3b3bf7a33056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.opblock-summary.opblock-summary-put > button.opblock-summary-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='operations-Gráfico-f9953321dcc2f4a2f2f9251eb83d1e89']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43670966-d8f8-4304-8373-ad6b253b8b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>put ​/api​/graphic​/{graphic}</value>
      <webElementGuid>900bdb17-e36d-4f33-9ed1-a8fa1fbaa024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95adb869-61f7-4e43-b7ea-a92cc71a53ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opblock-summary-control</value>
      <webElementGuid>fd57efa5-dc9b-46cd-a672-39aca65bf414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PUT/api/graphic/{graphic}Actualizar un gráfico existente por su ID</value>
      <webElementGuid>d044bca9-e7c2-47e9-9087-c8fec7dee029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operations-Gráfico-f9953321dcc2f4a2f2f9251eb83d1e89&quot;)/div[@class=&quot;opblock-summary opblock-summary-put&quot;]/button[@class=&quot;opblock-summary-control&quot;]</value>
      <webElementGuid>3d5c3891-c5fa-4466-94e2-4ec5151dd8fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='operations-Gráfico-f9953321dcc2f4a2f2f9251eb83d1e89']/div/button</value>
      <webElementGuid>14c5934d-13fd-407f-aa99-57f33572aeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No links'])[20]/following::button[1]</value>
      <webElementGuid>55c8ad83-a044-4e05-a553-7bfb71260749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'Internal Server Error', '&quot;', '')])[6]/following::button[1]</value>
      <webElementGuid>1bfef8c3-c3c5-4918-b179-1a89715021d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/div/div/button</value>
      <webElementGuid>5352a5e5-8a6a-4208-b08b-83a4a33239a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'PUT/api/graphic/{graphic}Actualizar un gráfico existente por su ID' or . = 'PUT/api/graphic/{graphic}Actualizar un gráfico existente por su ID')]</value>
      <webElementGuid>55b37045-c18b-425a-8cac-04bfffe7786d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
