<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Iniciar SesinRegistrar</name>
   <tag></tag>
   <elementGuidId>2e324f47-5ceb-48d6-8b6b-ec91026f56cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.top-0.right-0.p-6.text-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b96d5ea9-c094-410f-9a45-e40f79356232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-0 right-0 p-6 text-right</value>
      <webElementGuid>a1d35baf-d010-4439-830d-2150ba44f91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iniciar SesiónRegistrar</value>
      <webElementGuid>9eb7dcb3-586d-4378-aab2-8e4022e0e111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;relative sm:justify-center sm:items-center min-h-screen bg-dots-darker bg-center bg-gray-100 dark:bg-dots-lighter dark:bg-gray-900 selection:bg-red-500 selection:text-white&quot;]/div[@class=&quot;top-0 right-0 p-6 text-right&quot;]</value>
      <webElementGuid>dc6f980d-f690-446d-b0d5-e0d89f3fa573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div</value>
      <webElementGuid>9d34fd85-db36-4715-a34d-7054b7951834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>9e10b99a-a489-4f33-819f-9e11cf574d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Iniciar SesiónRegistrar' or . = 'Iniciar SesiónRegistrar')]</value>
      <webElementGuid>05893044-917d-4c99-a49a-e85d3b92871b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
