<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea Actual_current_password</name>
   <tag></tag>
   <elementGuidId>c73ecd5a-1612-43fa-bf2c-28da9c89a0de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#current_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='current_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dfe264f-8110-49ba-bc6d-494a86e9ecca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm mt-1 block w-full</value>
      <webElementGuid>ffb01351-3691-4a8d-aa65-a8cc74ef0a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>current_password</value>
      <webElementGuid>8d1d7444-219b-4595-8908-ec27884e1d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6a0f5a90-9d6e-42b9-b2e8-e7358f5e07f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>2ed214d3-1fc5-40cc-9cbb-fe6da384fc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current_password&quot;)</value>
      <webElementGuid>f75c94f7-90ce-42ac-8ca9-b4a80995c90a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='current_password']</value>
      <webElementGuid>a0531724-814e-4ef4-99c4-a42d1ad14335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div[2]/section/form/div/input</value>
      <webElementGuid>32429b29-6c67-4339-98b4-e78d1b77844a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section/form/div/input</value>
      <webElementGuid>40a96c19-b37a-4f2b-938d-953197de71f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'current_password' and @type = 'password']</value>
      <webElementGuid>01204e9e-b8a1-4071-a8db-ca2921281e4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
