<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Copiar</name>
   <tag></tag>
   <elementGuidId>ff5a0b0e-02a6-4615-9907-bdae8a546a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.copy-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo token de autenticación'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d09280c1-d2ab-4b14-bd5f-7efb41b6357e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>copy-text</value>
      <webElementGuid>aeea8a1b-8dab-44e8-9577-973be5fac2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copiar</value>
      <webElementGuid>dff69674-dfda-442a-ac0d-0addf222cb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;font-sans antialiased&quot;]/div[@class=&quot;fixed inset-0 overflow-y-auto px-4 py-6 sm:px-0 z-50&quot;]/div[@class=&quot;mb-6 bg-white dark:bg-gray-800 rounded-lg overflow-hidden shadow-xl transform transition-all sm:w-full sm:mx-auto sm:max-w-2xl&quot;]/div[@class=&quot;p-6&quot;]/div[@class=&quot;mt-6&quot;]/div[@class=&quot;relative&quot;]/button[@class=&quot;flex items-center absolute right-2 top-1/2 transform -translate-y-1/2 px-3 py-2 text-xs font-medium text-gray-600 hover:text-blue-700&quot;]/span[@class=&quot;copy-text&quot;]</value>
      <webElementGuid>96c4d45d-b96c-4ce8-9a97-3b6e32e3272b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo token de autenticación'])[1]/following::span[1]</value>
      <webElementGuid>2c630a4f-dfad-4243-af47-7dae02de2dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copiar']/parent::*</value>
      <webElementGuid>9909eac3-e132-4796-9b74-c8b23cec1169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>a7a18eb5-1b13-44eb-9cd3-40d53c4ccb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Copiar' or . = 'Copiar')]</value>
      <webElementGuid>f99d8a29-ccfa-45f3-866b-8c961fe19983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
