<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Variable Z_z</name>
   <tag></tag>
   <elementGuidId>ccfd12b2-1320-41a0-8a6e-142481936792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#z</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='z']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e9cd575-59dd-4a35-afba-0356c0619523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4a3949f0-795e-4cca-b126-b1f455e188fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>z</value>
      <webElementGuid>eb19db28-eab7-4f69-a9fd-7081664f0fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-gray-300 border rounded-md p-2</value>
      <webElementGuid>931c73e9-fc92-43f5-b0f9-131f01779643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>6b303df0-a35b-4d8d-be44-48ef9680a403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;z&quot;)</value>
      <webElementGuid>a4381757-65cb-4079-8c35-49dc9b69d09f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='z']</value>
      <webElementGuid>859f7e33-a477-4d80-8a62-2957bb3227c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div/div/div/div/div/div/div[8]/input</value>
      <webElementGuid>89958bd6-d896-4cef-a455-3253782cb753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>8847ea4f-6436-4cec-b065-0eb6db857efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'z']</value>
      <webElementGuid>05ca0e11-bff0-4d74-a345-5dc714a15605</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
