<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de Pasos_stepSize</name>
   <tag></tag>
   <elementGuidId>61e3249a-2ff7-40ab-aba0-23489bf215af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stepSize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stepSize']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d563266-e1d2-42bd-9aa5-12dd20e47e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3ce3c3fa-93c2-4935-8023-95a7dd250ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stepSize</value>
      <webElementGuid>7a386449-c7b9-4973-9741-b92781b014b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-gray-300 border rounded-md p-2</value>
      <webElementGuid>ebc94eb0-4c12-4488-a195-d694b0da433b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>44590ac3-e9f0-475c-9ff4-cdbdbc51f696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepSize&quot;)</value>
      <webElementGuid>12250317-2484-421c-832f-dc7a095a7eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stepSize']</value>
      <webElementGuid>3f3633f4-999c-4531-af07-b629ea49166d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>0b15ba8f-63c1-4a03-9c00-a74a99d20419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d3371c20-acd3-43d7-af3a-ca8b994ddf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'stepSize']</value>
      <webElementGuid>0183d009-136b-4fa2-b49a-d890bed3be95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
