<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parmetro c_c</name>
   <tag></tag>
   <elementGuidId>80003e96-982c-4008-8c86-c555571b4ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c65e9b97-9967-4fc2-80af-ec9a6e254720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0abe1b4e-6dd3-4b94-aa6d-8990b8e06780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>6fc13289-ea85-4dfd-b6c8-e0e1a34315cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-gray-300 border rounded-md p-2</value>
      <webElementGuid>3bdd786e-c5ae-467d-a3a3-7d79770e313b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>28c415c0-41da-4749-8f94-72d2ac858e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c&quot;)</value>
      <webElementGuid>c3b84205-7c29-4abe-b30f-b9cbe9db3457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c']</value>
      <webElementGuid>8ddc485d-2492-451f-9c09-588c53401aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div/div/div/div/div/div/div[5]/input</value>
      <webElementGuid>a940e54a-296d-41e2-8647-18d44c7f732b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>08b4de59-8dda-4039-8716-a1a5256ae91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'c']</value>
      <webElementGuid>32214ebd-556f-43a0-8dc8-3aed5091ebb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
