<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de Puntos_pointsNumber</name>
   <tag></tag>
   <elementGuidId>04afaf6c-8b47-4a6d-af2c-6dcd239f58b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pointsNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pointsNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7801ac2-9f30-4af0-94eb-556350a6787f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d38d8a52-5352-4edf-b37c-90a1241379c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pointsNumber</value>
      <webElementGuid>dbc25c3a-b9af-4a41-a7f4-f71e5ecc187b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-gray-300 border rounded-md p-2</value>
      <webElementGuid>d060b817-28d6-4a6e-a1b1-00014c6c6e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e194bc8e-f34c-4f3e-81eb-72756804f75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pointsNumber&quot;)</value>
      <webElementGuid>e3b1ce34-d7da-48e9-9610-994ab46003a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pointsNumber']</value>
      <webElementGuid>7df8135f-077b-4748-b93a-a86770444381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>d9293edf-49b4-4eaf-9939-532163c55b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b6228937-173b-4f24-8d65-5943146b3945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'pointsNumber']</value>
      <webElementGuid>0bff3ec3-541c-4775-856d-8ed33bec98f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>29e31072-04b1-47fe-b2e3-87b5a62213b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
