<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Variable X_x</name>
   <tag></tag>
   <elementGuidId>cbc58cc4-ae1c-4dea-b829-0bfaf9bc981f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='x']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79747f5f-b279-4a8c-bf5f-1d680ee2c547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>faeb6635-b257-438f-b48c-5fe7c9fe6eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>605d5130-1c8d-46ab-9c18-659b1417b3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-gray-300 border rounded-md p-2</value>
      <webElementGuid>0f9f982d-2aac-4fca-9bd0-8e89167b9741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>6f580811-a9ed-478b-a5d8-ab4f2b4976b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;x&quot;)</value>
      <webElementGuid>85f4491b-5fb8-4ca9-9d72-312b20c52b15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='x']</value>
      <webElementGuid>f2e1804c-f696-44b9-bbf3-a41af258bcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div/div/div/div/div/div/div[6]/input</value>
      <webElementGuid>1778e13e-d2dd-4c9f-b5a3-bfb6de5e621a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>027580cc-29c7-4f50-b09a-36c35fda652b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'x']</value>
      <webElementGuid>5f08c4bf-75c3-45a2-a0d7-3cdf7d939ff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
