<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Variable Y_y</name>
   <tag></tag>
   <elementGuidId>7570bcbd-fba7-4035-8353-8cd83404f679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#y</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='y']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9c8b615-7dca-47c3-87d4-2f583fa13396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4e9f96ba-e731-478e-bfd7-02cabb610e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>y</value>
      <webElementGuid>a201814c-8320-444c-835a-1da26bdf53eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-gray-300 border rounded-md p-2</value>
      <webElementGuid>86fb8b08-b663-4e0b-8abe-01f31a541e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>3190fa37-7ca5-42e0-82ce-414e37405aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;y&quot;)</value>
      <webElementGuid>5ca88724-0a78-4262-98bf-2719b374443e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='y']</value>
      <webElementGuid>293a7564-5252-4519-9c21-c99d836019e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div/div/div/div/div/div/div[7]/input</value>
      <webElementGuid>11d02edb-59ae-4cbb-aaa3-a2e8424f349a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>260f19cf-e72b-4119-a4b9-427f2d3be7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'y']</value>
      <webElementGuid>a493ba8b-aca3-4f4d-adff-3c081f2520e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
