<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Todos los atractores.Atractor de Ros_9cfb6d</name>
   <tag></tag>
   <elementGuidId>be42822c-9b72-4d29-b3af-4b55315d21f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a42161b7-9d05-4a21-899f-8c87ef5af1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>ef34f4f4-d015-4496-bb09-47f1c1dca960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>88d296ec-6ce7-4816-9426-cc77cba0dce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-11/12 mx-auto text-base dark:bg-gray-500 dark:text-white border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md</value>
      <webElementGuid>f7ca8bef-370a-4fe9-b177-90018eab6077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Todos los atractores...Atractor de RosslerAtractor de LorenzAtractor de ChenAtractor de Sprott</value>
      <webElementGuid>f4dad291-e2aa-45d9-b320-563f9ef7b728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type&quot;)</value>
      <webElementGuid>46f87bce-6534-4de8-81a6-5bfd2891dbaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='type']</value>
      <webElementGuid>2521e28c-c853-48b8-80c4-ef6815995666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div/div/div/select</value>
      <webElementGuid>2743cb27-ae3c-4139-a0d9-8c4d047d108b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtro por tipo'])[1]/following::select[1]</value>
      <webElementGuid>520ff004-51ff-42d2-a939-9a541cbb5b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Graficación: Historial'])[1]/following::select[1]</value>
      <webElementGuid>75710b39-cdfc-42ae-a4bd-7463b6355752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtro por título'])[1]/preceding::select[1]</value>
      <webElementGuid>48887c2f-bd42-4e2f-ad6e-cfcf3c7cef44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtro por fecha desde'])[1]/preceding::select[1]</value>
      <webElementGuid>e713f461-64db-4579-b178-0cd4b95e7a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6771f213-4293-4642-9938-b0ff3036a152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'type' and @id = 'type' and (text() = 'Todos los atractores...Atractor de RosslerAtractor de LorenzAtractor de ChenAtractor de Sprott' or . = 'Todos los atractores...Atractor de RosslerAtractor de LorenzAtractor de ChenAtractor de Sprott')]</value>
      <webElementGuid>8a4e5147-fb1e-4b14-9b62-031ac5ff5592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
