<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione el atractor.Atractor de R_8c46b5</name>
   <tag></tag>
   <elementGuidId>d59fc30c-dafa-4bbb-ad5a-214effe2b4ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#atractor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='atractor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a360ebcd-0a3d-48a0-90ff-c1602dac2e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>atractor</value>
      <webElementGuid>d860cb62-6471-4f98-a787-57eaa224ab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>atractor</value>
      <webElementGuid>3ddc6fff-67f6-46d3-b85d-8a24649b7326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-11/12 mx-auto my-10 text-base dark:bg-gray-500 dark:text-white border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md</value>
      <webElementGuid>6bc70e43-6082-4aea-a884-ff8c15ca54a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione el atractor...Atractor de RosslerAtractor de LorenzAtractor de ChenAtractor de Sprott</value>
      <webElementGuid>332e2e96-bb69-4e65-9032-ba0972c72305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atractor&quot;)</value>
      <webElementGuid>a30d7a45-5a5b-4a46-ba2e-e0d8f714c521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='atractor']</value>
      <webElementGuid>86ab4ac5-385c-44d5-a53d-3b3024660b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div/div/select</value>
      <webElementGuid>8745dbbe-e9ac-4daf-88f6-eb4954cb4a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Graficar un Atractor Caótico'])[1]/following::select[1]</value>
      <webElementGuid>d7c38521-0088-4a6b-987a-fc9d8c971a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'atractor', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>fb56b155-43ad-49b2-b6e6-2b00949676d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9aa5357b-bb28-48fa-b4ba-9a761a6416c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'atractor' and @id = 'atractor' and (text() = 'Seleccione el atractor...Atractor de RosslerAtractor de LorenzAtractor de ChenAtractor de Sprott' or . = 'Seleccione el atractor...Atractor de RosslerAtractor de LorenzAtractor de ChenAtractor de Sprott')]</value>
      <webElementGuid>78e1f878-46f2-4f75-8ad5-36c91c866da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Graficación: Dibujar Atractor'])[1]/following::select[1]</value>
      <webElementGuid>e11449db-b2ed-4e75-af3a-22e4c3d1942b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
