<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Perfil</name>
   <tag></tag>
   <elementGuidId>cad2fed0-908d-42a7-ad39-85cb507590dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/nav/div/div/div[2]/div/div/div[3]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8a5ed4b0-5fc8-4bfc-814c-d7e952114bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-4 py-2 text-left text-sm leading-5 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus:bg-gray-100 dark:focus:bg-gray-800 transition duration-150 ease-in-out</value>
      <webElementGuid>57f28be1-c701-4dfd-9776-3d2c504a9e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/profile</value>
      <webElementGuid>6327dfbe-7980-4c3d-a47b-d75265ef2550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Perfil </value>
      <webElementGuid>f8ac3559-11b1-4787-a358-7b859b3963b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;min-h-screen bg-gray-100 dark:bg-gray-900&quot;]/nav[@class=&quot;bg-white dark:bg-gray-800 border-b border-gray-100 dark:border-gray-700&quot;]/div[@class=&quot;max-w-7xl mx-auto px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex justify-between h-16&quot;]/div[@class=&quot;hidden sm:flex sm:items-center sm:ml-6&quot;]/div[@class=&quot;ml-3 relative&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;absolute z-50 mt-2 rounded-md shadow-lg w-48 origin-top-right right-0&quot;]/div[@class=&quot;rounded-md ring-1 ring-black ring-opacity-5 py-1 bg-white dark:bg-gray-700&quot;]/a[@class=&quot;block w-full px-4 py-2 text-left text-sm leading-5 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus:bg-gray-100 dark:focus:bg-gray-800 transition duration-150 ease-in-out&quot;]</value>
      <webElementGuid>a264a52a-e8dd-4925-90de-4c167a18c825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/nav/div/div/div[2]/div/div/div[3]/div/a</value>
      <webElementGuid>8f53b36c-59c8-42cf-8668-dccd96e4e20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thalía Fernanda Zárate'])[1]/following::a[1]</value>
      <webElementGuid>310e0bfb-d287-4f64-9d49-43277d6d1ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perfil']/parent::*</value>
      <webElementGuid>6f22948e-a574-4291-a24d-97491df994af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/profile']</value>
      <webElementGuid>4d396868-849c-4b2f-9c60-63923baf5bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>bc0ef819-46ae-4896-97be-9921d1edcd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/profile' and (text() = ' Perfil ' or . = ' Perfil ')]</value>
      <webElementGuid>bca39803-a9f8-4d73-8a4a-c76330b109a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thalía Zárate'])[1]/following::a[1]</value>
      <webElementGuid>1aaa5d77-daa1-45ac-8b55-f515951e3c21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
