<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filtro por fecha desdeFiltro por fecha _29f7df</name>
   <tag></tag>
   <elementGuidId>08145452-e67a-4829-b9af-dd20be80359a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/main/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0174ccff-bdcf-409c-8556-b9eb8a94bcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-w-7xl mx-auto sm:px-6 lg:px-8</value>
      <webElementGuid>89e3802c-9cca-4463-8169-8b0027d5d808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filtro por fecha desdeFiltro por fecha hastaNúmero de Gráficos por Tiposprott1lorenz1chen1rossler2Gráficos estadisticos por tipoBarrasDispersión2023-07-2500.20.40.60.81SprottFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.20.40.60.81LorenzFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.20.40.60.81ChenFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.511.52RosslerFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        </value>
      <webElementGuid>6be55883-10fa-4749-9dbc-d8801cfc3cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;min-h-screen bg-gray-100 dark:bg-gray-900&quot;]/main[1]/div[@class=&quot;py-12&quot;]/div[@class=&quot;max-w-7xl mx-auto sm:px-6 lg:px-8&quot;]</value>
      <webElementGuid>c83d9d74-3f04-432b-8714-2874f17e7d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div</value>
      <webElementGuid>aa9a7962-8535-442a-9a64-108f63a65494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[2]</value>
      <webElementGuid>3620aa0e-c53e-43d5-8b01-adae552806a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div</value>
      <webElementGuid>d7e02ec9-ef98-48ec-9d54-96c903ea2348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Filtro por fecha desdeFiltro por fecha hastaNúmero de Gráficos por Tiposprott1lorenz1chen1rossler2Gráficos estadisticos por tipoBarrasDispersión2023-07-2500.20.40.60.81SprottFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.20.40.60.81LorenzFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.20.40.60.81ChenFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.511.52RosslerFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        ' or . = 'Filtro por fecha desdeFiltro por fecha hastaNúmero de Gráficos por Tiposprott1lorenz1chen1rossler2Gráficos estadisticos por tipoBarrasDispersión2023-07-2500.20.40.60.81SprottFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.20.40.60.81LorenzFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.20.40.60.81ChenFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        BarrasDispersión2023-07-2500.511.52RosslerFechasCantidad   .cls-0{fill:#000;}  .cls-1{fill:#FFF;}  .cls-2{fill:#F26;}  .cls-3{fill:#D69;}  .cls-4{fill:#BAC;}  .cls-5{fill:#9EF;}  plotly-logomark                        ')]</value>
      <webElementGuid>200a69f0-de20-4bc0-9989-3e2de3463771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
