<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BarrasDispersin</name>
   <tag></tag>
   <elementGuidId>cb1dee64-dd82-4287-bc10-b31d19219375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chart-type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='chart-type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>65156e3e-8f60-4719-89c5-8d16e7c63907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chart-type</value>
      <webElementGuid>9edbbf5d-dbf0-4882-baaf-f4d38539b22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto mb-5 block w-full sm:w-11/12 text-base dark:bg-gray-500 dark:text-white border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md</value>
      <webElementGuid>6218a50f-0d9f-48f7-b9c6-48278aff253b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BarrasDispersión</value>
      <webElementGuid>7ea0390b-2a4f-487c-aef1-c304c8bcb937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;min-h-screen bg-gray-100 dark:bg-gray-900&quot;]/main[1]/div[@class=&quot;py-12&quot;]/div[@class=&quot;max-w-7xl mx-auto sm:px-6 lg:px-8&quot;]/div[@class=&quot;bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg mt-5&quot;]/div[@class=&quot;p-6 text-gray-900 dark:text-gray-100&quot;]/div[@class=&quot;flex flex-wrap mt-5&quot;]/div[@class=&quot;w-full lg:w-1/2 xl:w-1/2 p-5&quot;]/div[@class=&quot;dark:bg-white bg-gray-800 p-4 flex flex-col justify-center stats-center shadow-md rounded-lg h-full&quot;]/div[1]/div[1]/select[@id=&quot;chart-type&quot;]</value>
      <webElementGuid>e5ae1495-8e59-4d91-bbac-872bbc01b99a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='chart-type']</value>
      <webElementGuid>e2a3af2f-eae2-482b-aab5-9fa44495e5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div[3]/div/div/div/div/div/div/select</value>
      <webElementGuid>51780181-0809-4fe5-a9a5-92534df6ad49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gráficos estadisticos por tipo'])[1]/following::select[1]</value>
      <webElementGuid>80752250-8705-4223-984d-194d95238a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rossler'])[1]/following::select[1]</value>
      <webElementGuid>d99cb77e-5e30-4263-ba8f-88456bcbd78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sprott'])[1]/preceding::select[1]</value>
      <webElementGuid>30a3cf2f-f953-42f1-8e8a-c4d8862a9ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fechas'])[1]/preceding::select[1]</value>
      <webElementGuid>bb6f4c04-a4bb-4bb4-b258-11e5346d7372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>16ec3193-ab4c-4d1b-9866-fe947408e058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'chart-type' and (text() = 'BarrasDispersión' or . = 'BarrasDispersión')]</value>
      <webElementGuid>4458a8d7-0bf9-4c5a-84bf-57f9d6839341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
